version: "3.7"

services: 
    django1:
        build: .
        restart: on-failure:10
        ports: 
            - "8000:8000"
        env_file: 
            - ../vagrant/vars.env
        depends_on: 
            - postgres_db
        volumes: 
            - ./project/:/usr/src/project
    django2:
        build: .
        restart: on-failure:10
        ports: 
            - "8001:8000"
        env_file: 
            - ../vagrant/vars.env
        depends_on: 
            - postgres_db
        volumes: 
            - ./project/:/usr/src/project
    postgres_db:
        image: postgres 
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        restart: always
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=cloud_db
    
        
volumes: 
    postgres_data: 