name: ci

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: mitosHermanos
          password: 33e9bee8-cce6-402f-8fe9-fc5f2f362128
